export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

export const EDIT_USER_PASSWORD_REQUEST = 'EDIT_USER_PASSWORD_REQUEST';
export const EDIT_USER_PASSWORD_SUCCESS = 'EDIT_USER_PASSWORD_SUCCESS';
export const EDIT_USER_PASSWORD_FAIL = 'EDIT_USER_PASSWORD_FAIL';
