export const CREATE_SETTING_REQUEST = 'CREATE_SETTING_REQUEST';
export const CREATE_SETTING_SUCCESS = 'CREATE_SETTING_SUCCESS';
export const CREATE_SETTING_FAIL = 'CREATE_SETTING_FAIL';

export const FETCH_SETTING_REQUEST = 'FETCH_SETTING_REQUEST';
export const FETCH_SETTING_SUCCESS = 'FETCH_SETTING_SUCCESS';
export const FETCH_SETTING_FAIL = 'FETCH_SETTING_FAIL';

export const EDIT_SETTING_REQUEST = 'EDIT_SETTING_REQUEST';
export const EDIT_SETTING_SUCCESS = 'EDIT_SETTING_SUCCESS';
export const EDIT_SETTING_FAIL = 'EDIT_SETTING_FAIL';
